#include: package:very_good_analysis/analysis_options.2.4.0.yaml
include: package:lint/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/models/*.dart"