name: geat
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  amplify_analytics_pinpoint: ^0.6.2
  amplify_api: ^0.6.2
  amplify_auth_cognito: ^0.6.2
  amplify_datastore: ^0.6.2
  amplify_flutter: ^0.6.2
  amplify_storage_s3: ^0.6.2
  anim_search_bar: ^2.0.2
  animated_text_kit: ^4.2.2
  auto_route: ^4.2.1
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  dartz: ^0.10.1
  device_preview: ^1.1.0
  division: ^0.9.0
  dough: ^1.0.3
  emoji_picker_flutter: ^1.3.0
  expandable: ^5.0.1
  file_picker: ^4.6.1
  flash: ^2.0.3+2
  flex_color_scheme: ^5.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_form_builder: ^7.4.0
  flutter_hooks: ^0.18.5+1
  flutter_image_compress: ^1.1.0
  flutter_local_notifications: ^9.7.0
  flutter_localizations:
    sdk: flutter
  flutter_lorem: ^2.0.0
  flutter_markdown: ^0.6.10+2
  flutter_quill: ^5.0.4
  flutter_staggered_grid_view: ^0.6.2
  formz: ^0.4.1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  image_picker_for_web: ^2.1.8
  injectable: ^1.5.3
  intl: ^0.17.0
  liquid_progress_indicator: ^0.4.0
  lottie: ^1.3.0
  markdown_quill: ^1.0.0
  material_floating_search_bar: ^0.3.7
  permission_handler: ^10.0.0
  pin_code_fields: ^7.4.0
  pinput: ^2.2.11
  popover: ^0.2.6+3
  responsive_framework: ^0.2.0
  rxdart: ^0.27.4
  salomon_bottom_bar: ^3.3.1
  settings_ui: ^2.0.2
  share_plus: ^4.0.10
  shimmer: ^2.0.0
  sizer: ^2.0.15
  speech_to_text: ^5.6.0
  tab_indicator_styler: ^2.0.0
  timeago: ^3.2.2
  timeline_tile: ^2.0.0
  translator: ^0.1.7
  upgrader: ^4.4.0
  uuid: ^3.0.6
  webview_flutter: ^3.0.4

dev_dependencies:
  auto_route_generator: ^4.2.0
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  lint: ^1.8.2
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/json/
