name: geat
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  amplify_analytics_pinpoint: ^0.6.12
  amplify_api: ^0.6.12
  amplify_auth_cognito: ^0.6.12
  amplify_datastore: ^0.6.12
  amplify_flutter: ^0.6.12
  amplify_storage_s3: ^0.6.12
  auto_route: ^5.0.4
  cached_network_image: ^3.2.3
  country_list_pick: ^1.0.1+6
  dbcrypt: ^2.0.0
  dio: ^4.0.6
  dio_cache_interceptor_hive_store: ^3.2.0
  dio_smart_retry: ^1.4.0
  division: ^0.9.0
  firebase_analytics: ^10.1.0
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  flash: ^2.0.5
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_animate: ^3.1.0
  flutter_hooks: ^0.18.5+1
  flutter_keyboard_visibility: ^5.4.0
  flutter_launcher_icons: ^0.11.0
  flutter_limited_checkbox: ^0.0.1
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^7.0.1
  flutter_staggered_grid_view: ^0.6.2
  formz: ^0.4.1
  freezed_annotation: ^2.2.0
  go_router: ^6.0.3
  google_fonts: ^4.0.1
  hooks_riverpod: ^2.1.3
  image_picker: ^0.8.6+1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  json_serializable: ^6.6.1
  liquid_progress_indicator: ^0.4.0
  lottie: ^2.2.0
  markdown_widget: ^2.0.0+1
  material_tag_editor: ^0.1.2
  parallax_rain: ^1.1.0
  path_provider: ^2.0.12
  permission_handler: ^10.2.0
  popover: ^0.2.8
  riverpod_annotation: ^1.1.1
  rxdart: ^0.27.7
  share_plus: ^6.3.0
  shimmer: ^2.0.0
  simple_animations: ^5.0.0+3
  sliding_clipped_nav_bar: ^3.1.0+4
  super_editor: ^0.2.3+1
  supercharged: ^2.1.1
  textfield_tags: ^2.0.2
  timeago: ^3.2.0
  timeline_tile: ^2.0.0
  translator: ^0.1.7
  upgrader: ^6.0.1
  uuid: ^3.0.6
  webview_flutter: ^3.0.1
  webview_flutter_plus: ^0.3.0+2

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_annotation: ^4.8.0
  lint: ^2.0.1
  mocktail: ^0.3.0
  retrofit_generator: ^4.2.0
  riverpod_generator: ^1.1.1
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/json/
    - assets/html/
