name: geat
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  auto_route: ^4.2.1
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.4.6
  cloud_functions: ^3.3.6
  dot_navigation_bar: ^1.0.1+4
  expandable: ^5.0.1
  firebase_analytics: ^9.3.3
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  firebase_storage: ^10.3.7
  flash: ^2.0.3+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  flutter_keyboard_visibility: ^5.0.3
  flutter_launcher_icons: ^0.10.0
  flutter_limited_checkbox: ^0.0.1
  flutter_local_notifications: ^9.7.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.12
  flutter_rating_bar: ^1.0.0-nullsafety.1
  flutter_staggered_grid_view: ^0.6.2
  formz: ^0.4.1
  freezed_annotation: ^2.1.0
  google_fonts: ^3.0.1
  hydrated_bloc: ^8.1.0
  image_picker: ^0.8.5+3
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  json_serializable: ^6.3.1
  liquid_progress_indicator: ^0.4.0
  lottie: ^1.3.0
  markdown: ^6.0.1
  material_tag_editor: ^0.1.2
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  popover: ^0.2.6+3
  rxdart: ^0.27.4
  share_plus: ^4.0.10
  shimmer: ^2.0.0
  simple_animations: ^5.0.0+2
  super_editor: ^0.2.2
  supercharged: ^2.1.1
  timeago: ^3.2.2
  timeline_tile: ^2.0.0
  translator: ^0.1.7
  upgrader: ^4.4.0
  uuid: ^3.0.6
  visibility_aware_state: ^1.0.5
  webview_flutter: ^3.0.4
  webview_flutter_plus: ^0.3.0+2

dev_dependencies:
  auto_route_generator: ^4.2.0
  bloc_test: ^9.1.0
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3
  json_annotation: ^4.6.0
  lint: ^1.8.2
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/json/
    - assets/html/
