// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Ji2b2KHmthYBuzPKxYdRwol8YKwPFsM',
    appId: '1:1199319639:web:15f37591c67c845c9e9112',
    messagingSenderId: '1199319639',
    projectId: 'geat-prod-7e685',
    authDomain: 'geat-prod-7e685.firebaseapp.com',
    storageBucket: 'geat-prod-7e685.appspot.com',
    measurementId: 'G-N7YK3VPS2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDciH5ZcBcx6lbXvAwcJ4Q5zryanUCPtVg',
    appId: '1:1199319639:android:1b33800009b0096c9e9112',
    messagingSenderId: '1199319639',
    projectId: 'geat-prod-7e685',
    storageBucket: 'geat-prod-7e685.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLB5cJYK6ZqsKcLLHtdDfavt4xvrXyTBg',
    appId: '1:1199319639:ios:c548a5b51c476f679e9112',
    messagingSenderId: '1199319639',
    projectId: 'geat-prod-7e685',
    storageBucket: 'geat-prod-7e685.appspot.com',
    iosClientId: '1199319639-5893h9i7tnlf0d33krolobtopn05r28s.apps.googleusercontent.com',
    iosBundleId: 'com.album.geat.geat',
  );
}
