// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKdhuLgqz4Jq2pArnhsT-UHBPG2TaI4Y4',
    appId: '1:591794008755:web:b641b4ed9e36d765ecb6c6',
    messagingSenderId: '591794008755',
    projectId: 'geat-dev',
    authDomain: 'geat-dev.firebaseapp.com',
    storageBucket: 'geat-dev.appspot.com',
    measurementId: 'G-ZCM88RPJ4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1_BO0S9AcvFMBZFcLO2pAVwIi3VCY33o',
    appId: '1:591794008755:android:68b4ec1a8678af62ecb6c6',
    messagingSenderId: '591794008755',
    projectId: 'geat-dev',
    storageBucket: 'geat-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF-v2jlalq216DLVy4WxdVBJMJHV47PII',
    appId: '1:591794008755:ios:abe44e4d8c360c3decb6c6',
    messagingSenderId: '591794008755',
    projectId: 'geat-dev',
    storageBucket: 'geat-dev.appspot.com',
    iosClientId: '591794008755-0bt82krsmssiluegnq2eml99f4hin1ss.apps.googleusercontent.com',
    iosBundleId: 'com.album.geat.geat.dev',
  );
}
