import 'package:flutter_limited_checkbox/flutter_limited_checkbox.dart';

final bookGenre = [
  FlutterLimitedCheckBoxModel(selectId: 1, selectTitle: 'Fantasy'),
  FlutterLimitedCheckBoxModel(selectId: 2, selectTitle: 'Science Fiction'),
  FlutterLimitedCheckBoxModel(selectId: 3, selectTitle: 'Dystopian'),
  FlutterLimitedCheckBoxModel(selectId: 4, selectTitle: 'Action & Adventure'),
  FlutterLimitedCheckBoxModel(selectId: 5, selectTitle: 'Mystery'),
  FlutterLimitedCheckBoxModel(selectId: 6, selectTitle: 'Horror'),
  FlutterLimitedCheckBoxModel(selectId: 7, selectTitle: 'Thriller & Suspense'),
  FlutterLimitedCheckBoxModel(selectId: 8, selectTitle: 'Historical Fiction'),
  FlutterLimitedCheckBoxModel(selectId: 9, selectTitle: 'Romance'),
  FlutterLimitedCheckBoxModel(selectId: 10, selectTitle: 'Women’s Fiction'),
  FlutterLimitedCheckBoxModel(
      selectId: 11, selectTitle: 'Contemporary Fiction'),
  FlutterLimitedCheckBoxModel(selectId: 12, selectTitle: 'Literary Fiction'),
  FlutterLimitedCheckBoxModel(selectId: 13, selectTitle: 'Magical Realism'),
  FlutterLimitedCheckBoxModel(selectId: 14, selectTitle: 'Graphic Novel'),
  FlutterLimitedCheckBoxModel(selectId: 15, selectTitle: 'Short Story'),
  FlutterLimitedCheckBoxModel(selectId: 16, selectTitle: 'Young Adult'),
  FlutterLimitedCheckBoxModel(selectId: 17, selectTitle: 'New Adult'),
  FlutterLimitedCheckBoxModel(selectId: 18, selectTitle: 'Children’s'),
  FlutterLimitedCheckBoxModel(
      selectId: 19, selectTitle: 'Memoir & Autobiography'),
  FlutterLimitedCheckBoxModel(selectId: 20, selectTitle: 'Biography'),
  FlutterLimitedCheckBoxModel(selectId: 21, selectTitle: 'Food & Drink'),
  FlutterLimitedCheckBoxModel(selectId: 22, selectTitle: 'Art & Photography'),
  FlutterLimitedCheckBoxModel(selectId: 23, selectTitle: 'Superhero'),
  FlutterLimitedCheckBoxModel(
      selectId: 24, selectTitle: 'Science-Fiction/Fantasy'),
  FlutterLimitedCheckBoxModel(selectId: 25, selectTitle: 'Slice-of-Life'),
  FlutterLimitedCheckBoxModel(selectId: 26, selectTitle: 'Self-help'),
  FlutterLimitedCheckBoxModel(selectId: 27, selectTitle: 'History'),
  FlutterLimitedCheckBoxModel(selectId: 28, selectTitle: 'Non-fiction'),
  FlutterLimitedCheckBoxModel(selectId: 29, selectTitle: 'Guide / How-to'),
  FlutterLimitedCheckBoxModel(selectId: 30, selectTitle: 'True Crime'),
  FlutterLimitedCheckBoxModel(selectId: 31, selectTitle: 'Essays'),
  FlutterLimitedCheckBoxModel(selectId: 32, selectTitle: 'Humor'),
  FlutterLimitedCheckBoxModel(selectId: 33, selectTitle: 'Travel'),
];
